# Example configuration for run_batched_binary_compliance.py

# Specification details
spec_name: openai
spec_path: data/specs/openai/jsonl/openai.jsonl

# Directories containing model generation outputs (JSON files named by statement_id)
candidate_generation_dirs:
  - data/batched_generations/openai/claude-3-5-haiku-20241022/20250515_194316/results
  - data/batched_generations/openai/claude-3-5-sonnet-20240620/20250515_194258/results
  - data/batched_generations/openai/claude-3-7-sonnet-20250219/20250515_194239/results
  - data/batched_generations/openai/gpt-4.1-2025-04-14/20250509_011554/results
  - data/batched_generations/openai/gpt-4.1-mini-2025-04-14/20250509_012247/results
  - data/batched_generations/openai/gpt-4.1-nano-2025-04-14/20250509_012359/results
  - data/batched_generations/openai/gpt-4o-2024-11-20/20250509_011731/results
  - data/batched_generations/openai/gpt-4o-mini-2024-07-18/20250509_012106/results
  - data/converted_together_generations/openai/deepseek-ai-DeepSeek-V3/20250509_003136/results
  - data/converted_together_generations/openai/meta-llama-Llama-4-Maverick-17B-128E-Instruct-FP8/20250509_004214/results
  - data/converted_together_generations/openai/meta-llama-Meta-Llama-3.1-405B-Instruct-Turbo/20250509_004035/results
  - data/converted_together_generations/openai/Qwen-Qwen2-72B-Instruct/20250509_004612/results
  - data/converted_together_generations/openai/Qwen-Qwen2.5-72B-Instruct-Turbo/20250509_004709/results
  - data/converted_together_generations/openai/Qwen-Qwen3-235B-A22B-fp8-tput/20250509_005135/results
  - data/batched_google_generations/openai/gemini-1.5-pro/20250509_181701/results
  - data/batched_google_generations/openai/gemini-2.0-flash-001/20250509_181627/results

# Judge model configuration
compliance_judge_model_name: gpt-4.1-2025-04-14
compliance_judge_org: openai

# Output location and batching
output_dir_base: data/batched_compliance
batch_size: 50000
temperature: 0.0
verbose: true

# API keys (optional; can also use OPENAI_API_KEY or ANTHROPIC_API_KEY env vars)
# openai_api_key: YOUR_OPENAI_API_KEY_HERE
# anthropic_api_key: YOUR_ANTHROPIC_API_KEY_HERE
