spec_path: "data/specs/google/jsonl/google.jsonl"
# Provide a list of candidate output directories, each containing statement_id.json files
candidate_generation_dirs:
  - data/batched_generations/google/claude-3-5-haiku-20241022/20250509_025611/results
  - data/batched_generations/google/claude-3-5-sonnet-20240620/20250509_025521/results
  - data/batched_generations/google/claude-3-7-sonnet-20250219/20250509_025246/results
  - data/batched_generations/google/gpt-4.1-2025-04-14/20250509_030411/results
  - data/batched_generations/google/gpt-4.1-mini-2025-04-14/20250509_030821/results
  - data/batched_generations/google/gpt-4.1-nano-2025-04-14/20250509_133549/results
  - data/batched_generations/google/gpt-4o-2024-11-20/20250509_030502/results
  - data/batched_generations/google/gpt-4o-mini-2024-07-18/20250509_030631/results
  - data/converted_together_generations/google/deepseek-ai-DeepSeek-V3/20250509_054133/results
  - data/converted_together_generations/google/meta-llama-Llama-4-Maverick-17B-128E-Instruct-FP8/20250509_021252/results
  - data/converted_together_generations/google/meta-llama-Meta-Llama-3.1-405B-Instruct-Turbo/20250509_024643/results
  - data/converted_together_generations/google/Qwen-Qwen2-72B-Instruct/20250509_035308/results
  - data/converted_together_generations/google/Qwen-Qwen2.5-72B-Instruct-Turbo/20250509_080640/results
  - data/converted_together_generations/google/Qwen-Qwen3-235B-A22B-fp8-tput/20250509_054141/results
  - data/batched_google_generations/google/gemini-1.5-pro/20250509_181503/results
  - data/batched_google_generations/google/gemini-2.0-flash-001/20250509_181448/results

# Output settings
output_dir_base: "data/rankings_google/"

# Ranking settings
ranking_org: "google"
ranking_model_name: "gemini-2.0-flash-001"
verbose: true
all_pairs: true
skip_existing: true
batched_generations_mode: true
